[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[project]
name = "panoptes_aggregation"
description = "Aggregation code for Zooniverse panoptes projects."
authors = [
    {name = "Coleman Krawczyk", email = "coleman@zooniverse.org"},
]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: Apache Software License"
]
dynamic = ["version"]
requires-python = ">=3.8,<3.11"
dependencies = [
    "beautifulsoup4>=4.8.1",
    "collatex>=2.2",
    "hdbscan>=0.8.20",
    "lxml>=4.4",
    "numpy>=1.22.0",
    "packaging>=20.1",
    "pandas>=1.0.0",
    "progressbar2>=3.39",
    "python-levenshtein>=0.12.0",
    "python-slugify>=3.0.0",
    "pyyaml>=5.1",
    "scikit-learn>=1.0.0",
    "scipy>=1.6.1",
    "werkzeug>=0.14",
    "shapely>=1.7.1",
]

[project.optional-dependencies]
online = [
    "flask>=2.0",
    "flask-cors>=3.0",
    "panoptes-client>=1.1",
    "requests>=2.4.2",
    "gunicorn>=20.0",
    "sentry-sdk[flask]>=0.13.5",
    "newrelic>=5.4.0",
    "gitpython>=3.0.0",
]
gui = [
    "Gooey>=1.0.8.1",
]
doc = [
    "matplotlib>=3.5.1",
    "myst-nb>=0.13.2",
    "sphinx>=2.2.2",
    "sphinxcontrib-httpdomain>=1.7.0",
    "sphinx_rtd_theme>=0.4.3",
]
test = [
    "coverage>=4.5.3",
    "coveralls>=3.0.0",
    "flake8>=3.7",
    "flake8-black>=0.1.1",
    "flake8-bugbear>=20.1.2",
    "pytest>=7.1.2",
    "pytest-subtests>=0.8.0",
]

[project.scripts]
panoptes_aggregation = "panoptes_aggregation.scripts.aggregation_parser:main"

[project.gui-scripts]
panoptes_aggregation_gui = "panoptes_aggregation.scripts.gui:gui"

[project.urls]
Documentation = "https://aggregation-caesar.zooniverse.org/docs"
Source = "https://github.com/zooniverse/aggregation-for-caesar"

[tool.pdm]
version = { source = "file", path = "panoptes_aggregation/version/__init__.py" }

[tool.pdm.build]
includes = [
    "panoptes_aggregation/scripts/icons/*.png",
    "panoptes_aggregation/scripts/icons/*.ico"
]
source-includes = [
    "panoptes_aggregation/scripts/icons/*.png",
    "panoptes_aggregation/scripts/icons/*.ico"
]

[tool.pdm.dev-dependencies]
[tool.coverage.run]
omit = [
    "*test*",
    "panoptes_aggregation/scripts/gui*.py",
    "panoptes_aggregation/scripts/no_gooey.py",
    "panoptes_aggregation/scripts/path_type.py"
]
source = ["panoptes_aggregation"]
command_line = "-m pytest"

[tool.coverage.report]
show_missing = true
