name: Publish to PyPi

on: workflow_dispatch

jobs:
  build-and-publish:
    name: Build python package and publish to PyPi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup PDM
      uses: pdm-project/setup-pdm@main
      with:
        python-version: "3.10"
        architecture: x64
        prerelease: true
        enable-pep582: false
    - name: Build
      run: pdm build
    - name: Publish to PyPi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
