name: Python tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Setup PDM
      uses: pdm-project/setup-pdm@main
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
        prerelease: true
        enable-pep582: false
    - name: Install dependencies
      env:
        PDM_USE_VENV: True
      run: |
        pdm sync --no-isolation --no-self -G online -G test -G doc
    - name: Run tests
      env:
        TRAVIS: true  # one test is skipped on CI and looks for this env value
      run: |
        pdm run coverage run
        pdm run coverage report
    - name: Coveralls
      if: ${{ matrix.python-version == "3.10" }}
      run: pdm run coveralls --service=github
