name: Python tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Setup PDM
      uses: pdm-project/setup-pdm@main
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
        prerelease: true
        enable-pep582: false
    - name: Install dependencies
      run: |
        pdm config python.use_venv True
        pdm install --no-editable --no-isolation -G online -G doc -G test
    - name: Run tests
      env:
        TRAVIS: true  # one test is skipped on CI and looks for this env value
      run: |
        coverage run
        coverage report
    - name: Coveralls
      if: ${{ matrix.python-version == "3.10" }}
      run: coveralls --service=github
